#replace the image if you built your own from a modified Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: ray-head
spec:
  type: "LoadBalancer"
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: plasma
    port: 12345
    targetPort: 12345
  selector:
    app: ray-head
---
apiVersion: v1
kind: Pod
metadata:
  name: ray-head
  labels:
    app: ray-head
spec:
  containers:
  - name: ray-head
    image: peng00/ray-kubernetes
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 6379
    - containerPort: 12345
    command: [ "/bin/bash", "-c", "--" ]
    args:
      - "ray start --head --redis-port 6379 --object-manager-port 12345 --node-ip-address $MY_POD_IP &&
        echo id_rsa.pub is - &&
        more ~/.ssh/id_rsa.pub &&
        echo export PATH=/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin >> ~/.bashrc &&
        while true; do sleep 30; done;"
#`&&` chains the commands so everything will be dependent on other lines succeeding. use `;` instead if a command is likely to cause an error.
